server:
  servlet:
    context-path: /petadopt
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petadopt?useSSL=false
    username: root
    password: 1223
  freemarker:
    request-context-attribute: request
  # 关闭静态资源缓存
  resources:
    chain:
      cache: false
  jpa:
    show-sql: true